### ISSUE TITLE
Consider always showing radius label of "1"

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/trig-tour#110]
@amanda-phet - I think it might be good to always show the radius label of "1", even when labels is not checked. It's so critical that students know this is a unit circle and so having it always clear that the radius is 1 seems important. The other labels can remain unlabeled, to keep things nice and simple. 

Amanda, what do you think?

**Comment by amanda-phet** [comment]
That's true it's important, but I'm not sure it's fundamental. Regardless of the circle radius, the ratio of the trig function will equal the same value. The radius of 1 is why the x-coordinate (in this example) is exactly the value of cos theta, but you can turn on labels to get to that learning goal.

![image](https://github.com/user-attachments/assets/2c1af37f-8410-4a05-844e-61b51c68108f)

It also ties the circle to the graph below, which has a max of 1 for this reason, and when labels are turned on you see all of the places where the value is 1. 

It's tough because I think all of the labels are super important! I really with theta was always indicated, and might even find that more important. 

So, I'm not sure what makes the most sense to do.

**Comment by amanda-phet** [comment]
Another idea- we could have labels on by default, and people can turn it off to reduce clutter?

**Comment by amanda-phet** [comment]
@kathy-phet and I discussed this today and would like the 1 on the radius and the theta on the angle to always be visible, if that's a straightforward change.

**Comment by jessegreenberg** [comment]
I think that is done, @amanda-phet can you please verify?

**Comment by amanda-phet** [comment]
Looks great! Thank you!
