### ISSUE TITLE
Grabbable pointer can cause too many turns

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#36]
There is no limit check for the grabbable pointer on the GraphView, so when the pointer is dragged out of bounds, the number of rotations can continue to grow:

![toomanyturnsimdizzy](https://cloud.githubusercontent.com/assets/6396244/9426502/31745f8a-4904-11e5-8c97-9a352a87f5af.PNG)

**Comment by jessegreenberg** [comment]
Fixed in the commit above.  

![offscreen](https://cloud.githubusercontent.com/assets/6396244/10120008/bd9e008e-6465-11e5-870d-49dc5b9ad283.PNG)

However, since 2.25 is the max number of rotations, the user can still pull the indicator arrow off of the panel before the dizzy PhET girl pops up (shown above).  If the max number of rotations is 2.125, the indicator arrow will always remain visible on the graph panel (shown below).

![onscreen](https://cloud.githubusercontent.com/assets/6396244/10120018/0fcd2858-6466-11e5-878d-de9c651c2e2a.PNG)

@dubson and @amanda-phet are you OK with the indicator going off screen or would you like to change the max number of rotations to 2.125?

**Comment by amanda-phet** [comment]
The max number of rotations is actually much larger. The user should be able to rotate the red point around the circle until the rotations reaches the border of the circle panel. I believe it is around 2 right now so that we can see the dizzyphetgirl image, but that maximum should be changed to be much larger. 

The red point on the graph becomes invisible/unusable after a little over 2 rotations, but technically the graph continues... we just don't see it.

**Comment by jessegreenberg** [comment]
I see, thanks, I didn't realize that was the design.  It was very explicit in the code that the user should not be able to increase the number of rotations past 2.25 turns.

It takes about 50 turns to get the the edge of the unit circle panel.  
![spheftyturns](https://cloud.githubusercontent.com/assets/6396244/10140528/3a272c60-65c5-11e5-80bb-dbcf82eb1f13.PNG)

**Comment by jessegreenberg** [comment]
Commit above extends the maximum angle to allow 25.25 rotations on the unit circle so that the dizzy PhET girl pops up at the point above. The spiral reaches the edge of the unit circle panel. Closing.
