### ISSUE TITLE
AccordionBox requires two children for de-linting

### ISSUE THREAD

**Issue by dubson** [phetsims/trig-tour#7]
I (MD) am using AccordonBox in trig-lab/view/GraphView, and my accordionBox has a nearly-empty content node consisting of one Text instance.  I am using AccordionBox merely to get the nice show/hide button with a title.  Issue: I get the error shown below when I try to de-lint.  Apparently, AccordionBox won't de-lint unless the display node has at least 2 children, otherwise the HBox is never instantiated.  

dubson@DUBSON-THINK ~/phetsims/trig-lab (master)
$ grunt
Running "jshint:allFiles" (jshint) task
Linting ../joist/js/NavigationBar.js ...ERROR
[L15:C11] W098: 'HBox' is defined but never used.
  var HBox = require( 'SCENERY/nodes/HBox' );

Warning: Task "jshint:allFiles" failed. Use --force to continue.

**Comment by jbphet** [comment]
This lint error does not appear to be related to the AccordionBox - it looks like it came from NavigationBar.js.  NavigationBar.js was undergoing some changes, and my guess is that @dubson just happened to catch a version with a lint error.  I just updated and built trig-lab with no problems, so I think the issue is probably fixed.  Assigning back to @dubson.

**Comment by jessegreenberg** [comment]
This issue can be closed, the sim builds cleanly.
